# This is a basic workflow to help you get started with Actions

name: Github Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # SDK Version to use.
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build Release
      run: dotnet build --configuration Release --no-restore
    
    - name: Create the package
      run: dotnet pack --configuration Release
      
    - name: Add GPR Source
      run: dotnet nuget add source --username tatlacas --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/tatlacas-com/index.json"
      
    - name: Publish the package to GPR
      run: dotnet nuget push bin/Release/*.nupkg
